### ISSUE TITLE
Please add in slideshare downloader a upload text file of URLs.

### ISSUE THREAD

**Issue by heyeanne34** [JVinuelas19/Slideshare-Scrapper#1]
Please add in slideshare downloader a upload text file of URLs. please add this I cant find any that could do this.. i have a lot of URLs of slideshare I want to download pls add this option that it accepts unlimited amount of URLs and I can set which in my filelocation I can save the downloads. i want to download it in my HDD... pls help

**Comment by JVinuelas19** [comment]
Hello heyeanne34, thank you for your interest in the slideshare scrapper. I will code that feature ASAP but please notice that i am not earning anything by doing this. If you are using my code and you find it useful please consider making a donation to me at the following link: https://www.paypal.com/donate/?hosted_button_id=7QSS3APP4TSGE

**Comment by JVinuelas19** [comment]
Well, this is it! Now the code can read from a txt file where you paste each URL in a separate line (if you don't do it this way it won't work). Just copy the path to the txt file and choose where you want to store the books.
